version: '3.7'

services:
  panel:
    image: ghcr.io/pterodactyl/panel:${PANEL_VERSION}
    restart: unless-stopped
    networks:
      - panel
      - caddy-reverse-proxy
    env_file:
      - .env
    depends_on:
      - mysql
      - cache
    environment:
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DATA_DIR}/panel/var:/app/var
      - ${DATA_DIR}/panel/logs:/app/log
    labels:
      caddy: ${PANEL_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 80}}"
  mysql:
    image: mariadb:10.5
    restart: unless-stopped
    networks:
      - panel
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}/mariadb:/var/lib/mysql
      - /etc/ssl/certs:/etc/ssl/certs:ro
  cache:
    image: redis:alpine
    restart: always
    networks:
      - panel

networks:
  caddy-reverse-proxy:
    external: true
  panel:
    internal: true
    ipam:
      config:
        - subnet: 172.31.0.0/16
