version: '3.7'

networks:
  caddy-reverse-proxy:
    external: true

services:
  wing:
    image: ghcr.io/pterodactyl/wings:${WING_VERSION}
    ports:
      - 2022:2022
    networks:
      - caddy-reverse-proxy
    env_file:
      - .env
    restart: unless-stopped
    working_dir: ${DATA_DIR_WING}
    environment:
      - TZ=${WING_TIMEZONE:-UTC}
    volumes:
      - ${DATA_DIR_WING}:${DATA_DIR_WING}
      - ${DATA_DIR}/wing/config:/etc/pterodactyl
      - ${DATA_DIR}/wing/log:/var/log/pterodactyl
      - /tmp/pterodactyl:/tmp/pterodactyl
      - ${WING_DOCKER_ROOT:-/var/lib/docker}:${WING_DOCKER_ROOT:-/var/lib/docker}
      - ${WING_DOCKER_SOCKET:-/var/run/docker.sock}:${WING_DOCKER_SOCKET:-/var/run/docker.sock}
      - /etc/ssl/certs:/etc/ssl/certs:ro
    labels:
      caddy: ${WING_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 443}}"
